server:
  port: 8081

spring:
  datasource:
    hikari:
      source:
        username: root
        password: rootpassword
        jdbc-url: jdbc:mariadb://localhost:33306/db_name
      replica:
        replica-List:
          -   name: replica1
              username: replica1
              password: rootpassword
              jdbc-url: jdbc:mariadb://localhost:43306/db_name
#          -   name: replica2
#              username: replica2
#              password: choiRootRoot
#              jdbc-url: jdbc:mysql://localhost:43307/interview_test
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #        use_sql_comments: true
        open-in-view: false
    jackson:
      deserialization:
        adjust-dates-to-context-time-zone: false
      time-zone: Asia/Seoul

kafka:
  consumer:
    group-id: user-command
  bootstrap-servers: localhost:9092
  topics:
    user-status: user-status

jwt:
  secret: alesdfjalwasdfdsflasgpa;sd[rekgjirjgoaiszjreqaosdghjshuihuag